# Generated by Django 2.1.1 on 2018-09-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dish_ingredients',
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_ingredients',
            field=models.ManyToManyField(to='demo.Ingredient'),
        ),
    ]
