# Generated by Django 2.1.1 on 2018-09-30 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20180930_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('dish_order', models.CharField(max_length=250)),
                ('feedback', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
