# Generated by Django 2.1.1 on 2018-09-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='could_improve',
            field=models.CharField(default='Things need work', max_length=250),
        ),
        migrations.AddField(
            model_name='feedback',
            name='liked',
            field=models.CharField(default='Liked everything', max_length=250),
        ),
    ]
