# Generated by Django 2.1.1 on 2018-09-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_remove_feedback_could_improve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='liked',
            new_name='feedback',
        ),
    ]
